language: cpp

compiler:
  - g++
  - clang
    
before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq libboost-all-dev libeigen3-dev libdevil-dev libglew-dev libassimp-dev glew-utils libglewmx-dev ubuntu-toolchain-r-test
    
script:
  - mkdir build
  - cd build
  - cmake ..
  - make all

notifications:
  email: none
