language: cpp
sudo: false
compiler:
  - g++
  - clang
    
script:
  - mkdir build
  - cd build
  - cmake ..
  - make all

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++
    - libboost-all-dev
    - libeigen3-dev
    - libdevil-dev
    - libglew-dev
    - libassimp-dev
    - glew-utils
    - libglewmx-dev

notifications:
  email: none
