language: cpp

compiler:
  - clang
  
    
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libboost-all-dev
    - libeigen3-dev
    - libdevil-dev
    - libglew-dev
    - libassimp-dev
    - glew-utils
    - libglewmx-dev
    - freeglut3-dev
    - libblas-dev

    
script:
  - mkdir build
  - cd build
  - cmake ..
  - make all

notifications:
  email: none
